[appearance]
font_name = "Inter"
background_color = "#fbf3db"
primary_color = "#0072d4"
secondary_color = "#3a4d53"
success_color = "#489100"
danger_color = "#d2212d"
text_color = "#53676d"
workspace_colors = [ "#0072d4", "#ca4898", "#c25d1e" ]

[modules]
left = [ [ "Workspaces" , "WindowTitle" ] ]
center = [ ["Clock" ] ]
right = [ "MediaPlayer", [ "Tray", "Privacy", "Settings" ] ]
