[tools]
atuin = "latest"
bat = "latest"
bitwarden = "latest"
bun = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gum = "latest"
helix = "latest"
hyperfine = "latest"
jq = "latest"
jujutsu = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
taplo = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["node"]
