[tools]
bitwarden = "latest"
bun = "latest"
claude = "latest"
"github:openai/codex" = "latest"
"github:sst/opencode" = "latest"
gum = "latest"
node = "latest"
"npm:osgrep" = "latest"
uv = "latest"
[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["node"]
