[tools]
"aqua:openai/codex" = "latest"
bitwarden = "latest"
bun = "latest"
claude = "latest"
gum = "latest"
node = "latest"
"npm:osgrep" = "latest"
opencode = "latest"
uv = "latest"
[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["node"]

